-- Image display settings (focal point + zoom) for admin-controlled cropping

ALTER TABLE products
ADD COLUMN IF NOT EXISTS image_settings JSONB NOT NULL DEFAULT '{}';

ALTER TABLE gallery_images
ADD COLUMN IF NOT EXISTS focal_x REAL NOT NULL DEFAULT 50,
ADD COLUMN IF NOT EXISTS focal_y REAL NOT NULL DEFAULT 50,
ADD COLUMN IF NOT EXISTS zoom REAL NOT NULL DEFAULT 1;

ALTER TABLE collections
ADD COLUMN IF NOT EXISTS thumbnail_focal_x REAL NOT NULL DEFAULT 50,
ADD COLUMN IF NOT EXISTS thumbnail_focal_y REAL NOT NULL DEFAULT 50,
ADD COLUMN IF NOT EXISTS thumbnail_zoom REAL NOT NULL DEFAULT 1;

ALTER TABLE subcollections
ADD COLUMN IF NOT EXISTS thumbnail_focal_x REAL NOT NULL DEFAULT 50,
ADD COLUMN IF NOT EXISTS thumbnail_focal_y REAL NOT NULL DEFAULT 50,
ADD COLUMN IF NOT EXISTS thumbnail_zoom REAL NOT NULL DEFAULT 1;
